framework:
    secret:                           "sroze.io"
    trusted_proxies: ~
    test: ~
    session:
        storage_id:                    "session.storage.mock_file"

log_stream:
    url: https://localhost:8001
